# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telzir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.PositiveIntegerField(max_length=18),
        ),
    ]
