# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telzir', '0002_auto_20170927_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.PositiveIntegerField(),
        ),
    ]
