# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telzir', '0003_auto_20170927_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_plano', models.CharField(blank=True, choices=[('Pre-Pago', 'Pre-Pago'), ('Pos-Pago', 'Pos-Pago')], max_length=20, null=True)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
